### ISSUE TITLE
More generic math interface implement

### ISSUE THREAD

**Issue by ODtian** [Venomalia/AuroraLib.Core#3]
For example, `IBinaryInteger<Int24>` and `IMinMaxValue<Int24>`

**Comment by Venomalia** [comment]
What exactly do you need it for?

**Comment by ODtian** [comment]
@Venomalia To use set of method like `readlittleendian` which exist in `int`, `long` and `short` with generic, and access max min value with generic interface.

**Comment by Venomalia** [comment]
Ah ok, I didn't know that there are new interfaches in net8.
